// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: internal/proto/shortener.proto

// Package proto for generated proto files.
package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateBatchRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Urls          []*GenerateBatchRequest_BatchRequest `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBatchRequest) Reset() {
	*x = GenerateBatchRequest{}
	mi := &file_internal_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBatchRequest) ProtoMessage() {}

func (x *GenerateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBatchRequest.ProtoReflect.Descriptor instead.
func (*GenerateBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateBatchRequest) GetUrls() []*GenerateBatchRequest_BatchRequest {
	if x != nil {
		return x.Urls
	}
	return nil
}

type GenerateBatchResponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Urls          []*GenerateBatchResponse_BatchResponse `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBatchResponse) Reset() {
	*x = GenerateBatchResponse{}
	mi := &file_internal_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBatchResponse) ProtoMessage() {}

func (x *GenerateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBatchResponse.ProtoReflect.Descriptor instead.
func (*GenerateBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateBatchResponse) GetUrls() []*GenerateBatchResponse_BatchResponse {
	if x != nil {
		return x.Urls
	}
	return nil
}

type URLMappings struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Urls          []*URLMappings_URLMapping `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLMappings) Reset() {
	*x = URLMappings{}
	mi := &file_internal_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLMappings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLMappings) ProtoMessage() {}

func (x *URLMappings) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLMappings.ProtoReflect.Descriptor instead.
func (*URLMappings) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *URLMappings) GetUrls() []*URLMappings_URLMapping {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UserURLs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLs) Reset() {
	*x = UserURLs{}
	mi := &file_internal_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLs) ProtoMessage() {}

func (x *UserURLs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLs.ProtoReflect.Descriptor instead.
func (*UserURLs) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *UserURLs) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type StorageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCount     int64                  `protobuf:"varint,1,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	UrlCount      int64                  `protobuf:"varint,2,opt,name=url_count,json=urlCount,proto3" json:"url_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageStats) Reset() {
	*x = StorageStats{}
	mi := &file_internal_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStats) ProtoMessage() {}

func (x *StorageStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStats.ProtoReflect.Descriptor instead.
func (*StorageStats) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *StorageStats) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *StorageStats) GetUrlCount() int64 {
	if x != nil {
		return x.UrlCount
	}
	return 0
}

type URL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_internal_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *URL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GenerateBatchRequest_BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBatchRequest_BatchRequest) Reset() {
	*x = GenerateBatchRequest_BatchRequest{}
	mi := &file_internal_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBatchRequest_BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBatchRequest_BatchRequest) ProtoMessage() {}

func (x *GenerateBatchRequest_BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBatchRequest_BatchRequest.ProtoReflect.Descriptor instead.
func (*GenerateBatchRequest_BatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GenerateBatchRequest_BatchRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GenerateBatchRequest_BatchRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type GenerateBatchResponse_BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBatchResponse_BatchResponse) Reset() {
	*x = GenerateBatchResponse_BatchResponse{}
	mi := &file_internal_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBatchResponse_BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBatchResponse_BatchResponse) ProtoMessage() {}

func (x *GenerateBatchResponse_BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBatchResponse_BatchResponse.ProtoReflect.Descriptor instead.
func (*GenerateBatchResponse_BatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GenerateBatchResponse_BatchResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *GenerateBatchResponse_BatchResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type URLMappings_URLMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLMappings_URLMapping) Reset() {
	*x = URLMappings_URLMapping{}
	mi := &file_internal_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLMappings_URLMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLMappings_URLMapping) ProtoMessage() {}

func (x *URLMappings_URLMapping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLMappings_URLMapping.ProtoReflect.Descriptor instead.
func (*URLMappings_URLMapping) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{2, 0}
}

func (x *URLMappings_URLMapping) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URLMappings_URLMapping) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_internal_proto_shortener_proto protoreflect.FileDescriptor

const file_internal_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/shortener.proto\x12\tshortener\x1a\x1bgoogle/protobuf/empty.proto\"\xb2\x01\n" +
	"\x14GenerateBatchRequest\x12@\n" +
	"\x04urls\x18\x01 \x03(\v2,.shortener.GenerateBatchRequest.BatchRequestR\x04urls\x1aX\n" +
	"\fBatchRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"\xb0\x01\n" +
	"\x15GenerateBatchResponse\x12B\n" +
	"\x04urls\x18\x01 \x03(\v2..shortener.GenerateBatchResponse.BatchResponseR\x04urls\x1aS\n" +
	"\rBatchResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"\x8a\x01\n" +
	"\vURLMappings\x125\n" +
	"\x04urls\x18\x01 \x03(\v2!.shortener.URLMappings.URLMappingR\x04urls\x1aD\n" +
	"\n" +
	"URLMapping\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\"\x1e\n" +
	"\bUserURLs\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"J\n" +
	"\fStorageStats\x12\x1d\n" +
	"\n" +
	"user_count\x18\x01 \x01(\x03R\tuserCount\x12\x1b\n" +
	"\turl_count\x18\x02 \x01(\x03R\burlCount\"\x17\n" +
	"\x03URL\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xba\x03\n" +
	"\x14ShortenerHandlerGrpc\x12/\n" +
	"\rShort2LongURL\x12\x0e.shortener.URL\x1a\x0e.shortener.URL\x12*\n" +
	"\bGenerate\x12\x0e.shortener.URL\x1a\x0e.shortener.URL\x12R\n" +
	"\rGenerateBatch\x12\x1f.shortener.GenerateBatchRequest\x1a .shortener.GenerateBatchResponse\x12=\n" +
	"\vGetUserURLs\x12\x16.google.protobuf.Empty\x1a\x16.shortener.URLMappings\x12=\n" +
	"\x0eDeleteUserURLs\x12\x13.shortener.UserURLs\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x17.shortener.StorageStats\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x11Z\x0fshortener/protob\x06proto3"

var (
	file_internal_proto_shortener_proto_rawDescOnce sync.Once
	file_internal_proto_shortener_proto_rawDescData []byte
)

func file_internal_proto_shortener_proto_rawDescGZIP() []byte {
	file_internal_proto_shortener_proto_rawDescOnce.Do(func() {
		file_internal_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_shortener_proto_rawDesc), len(file_internal_proto_shortener_proto_rawDesc)))
	})
	return file_internal_proto_shortener_proto_rawDescData
}

var file_internal_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_proto_shortener_proto_goTypes = []any{
	(*GenerateBatchRequest)(nil),                // 0: shortener.GenerateBatchRequest
	(*GenerateBatchResponse)(nil),               // 1: shortener.GenerateBatchResponse
	(*URLMappings)(nil),                         // 2: shortener.URLMappings
	(*UserURLs)(nil),                            // 3: shortener.UserURLs
	(*StorageStats)(nil),                        // 4: shortener.StorageStats
	(*URL)(nil),                                 // 5: shortener.URL
	(*GenerateBatchRequest_BatchRequest)(nil),   // 6: shortener.GenerateBatchRequest.BatchRequest
	(*GenerateBatchResponse_BatchResponse)(nil), // 7: shortener.GenerateBatchResponse.BatchResponse
	(*URLMappings_URLMapping)(nil),              // 8: shortener.URLMappings.URLMapping
	(*empty.Empty)(nil),                         // 9: google.protobuf.Empty
}
var file_internal_proto_shortener_proto_depIdxs = []int32{
	6,  // 0: shortener.GenerateBatchRequest.urls:type_name -> shortener.GenerateBatchRequest.BatchRequest
	7,  // 1: shortener.GenerateBatchResponse.urls:type_name -> shortener.GenerateBatchResponse.BatchResponse
	8,  // 2: shortener.URLMappings.urls:type_name -> shortener.URLMappings.URLMapping
	5,  // 3: shortener.ShortenerHandlerGrpc.Short2LongURL:input_type -> shortener.URL
	5,  // 4: shortener.ShortenerHandlerGrpc.Generate:input_type -> shortener.URL
	0,  // 5: shortener.ShortenerHandlerGrpc.GenerateBatch:input_type -> shortener.GenerateBatchRequest
	9,  // 6: shortener.ShortenerHandlerGrpc.GetUserURLs:input_type -> google.protobuf.Empty
	3,  // 7: shortener.ShortenerHandlerGrpc.DeleteUserURLs:input_type -> shortener.UserURLs
	9,  // 8: shortener.ShortenerHandlerGrpc.GetStats:input_type -> google.protobuf.Empty
	9,  // 9: shortener.ShortenerHandlerGrpc.Ping:input_type -> google.protobuf.Empty
	5,  // 10: shortener.ShortenerHandlerGrpc.Short2LongURL:output_type -> shortener.URL
	5,  // 11: shortener.ShortenerHandlerGrpc.Generate:output_type -> shortener.URL
	1,  // 12: shortener.ShortenerHandlerGrpc.GenerateBatch:output_type -> shortener.GenerateBatchResponse
	2,  // 13: shortener.ShortenerHandlerGrpc.GetUserURLs:output_type -> shortener.URLMappings
	9,  // 14: shortener.ShortenerHandlerGrpc.DeleteUserURLs:output_type -> google.protobuf.Empty
	4,  // 15: shortener.ShortenerHandlerGrpc.GetStats:output_type -> shortener.StorageStats
	9,  // 16: shortener.ShortenerHandlerGrpc.Ping:output_type -> google.protobuf.Empty
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_shortener_proto_init() }
func file_internal_proto_shortener_proto_init() {
	if File_internal_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_shortener_proto_rawDesc), len(file_internal_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_shortener_proto_goTypes,
		DependencyIndexes: file_internal_proto_shortener_proto_depIdxs,
		MessageInfos:      file_internal_proto_shortener_proto_msgTypes,
	}.Build()
	File_internal_proto_shortener_proto = out.File
	file_internal_proto_shortener_proto_goTypes = nil
	file_internal_proto_shortener_proto_depIdxs = nil
}
